//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z.ExtensionMethods.EF6.Examples
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityWithAllColumn2
    {
        public int ID { get; set; }
        public Nullable<long> BitIntColumn { get; set; }
        public byte[] BinaryColumn { get; set; }
        public Nullable<bool> BitColumn { get; set; }
        public string CharColumn { get; set; }
        public Nullable<System.DateTime> DateColumn { get; set; }
        public Nullable<System.DateTime> DateTimeColumn { get; set; }
        public Nullable<System.DateTime> DateTime2Column { get; set; }
        public Nullable<System.DateTimeOffset> DateTimeOffsetColumn { get; set; }
        public Nullable<decimal> DecimalColumn { get; set; }
        public Nullable<double> FloatColumn { get; set; }
        public byte[] ImageColumn { get; set; }
        public Nullable<int> IntColumn { get; set; }
        public Nullable<decimal> MoneyColumn { get; set; }
        public string NCharColumn { get; set; }
        public string NTextColumn { get; set; }
        public Nullable<decimal> NumericColumn { get; set; }
        public string NVarcharColumn { get; set; }
        public string NVarcharMaxColumn { get; set; }
        public Nullable<float> RealColumn { get; set; }
        public Nullable<System.DateTime> SmallDateTimeColumn { get; set; }
        public Nullable<short> SmallIntColumn { get; set; }
        public Nullable<decimal> SmallMoneyColumn { get; set; }
        public string TextColumn { get; set; }
        public Nullable<System.TimeSpan> TimeColumn { get; set; }
        public byte[] TimestampColumn { get; set; }
        public Nullable<byte> TinyIntColumn { get; set; }
        public Nullable<System.Guid> UniqueIdentifierColumn { get; set; }
        public byte[] VarBinaryColumn { get; set; }
        public byte[] VarBinaryMaxColumn { get; set; }
        public string VarcharColumn { get; set; }
        public string VarcharMaxColumn { get; set; }
        public string XmlColumn { get; set; }
    }
}
