//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z.ExtensionMethods.EF6.Examples
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkCopyTest2
    {
        public int ID1 { get; set; }
        public int ID2 { get; set; }
        public Nullable<bool> ValueBit { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public string ValueString { get; set; }
    }
}
