//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z.ExtensionMethods.EF6.Examples
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestMapping2
    {
        public int PrimaryKeyColumn { get; set; }
        public int IntColumn { get; set; }
        public string VarcharColumn { get; set; }
    }
}
