using System;
using System.Collections.Generic;
using nucs.SystemCore;

namespace nucs.Windows.Keyboard {
    public enum KeyCode : ushort {
        None = 0,
        LButton = (ushort)1,
        RButton = (ushort)2,
        Cancel = (ushort)3,
        MButton = (ushort)4,
        XButton1 = (ushort)5,
        XButton2 = (ushort)6,
        Back = (ushort)8,
        Tab = (ushort)9,
        Clear = (ushort)12,
        Return = (ushort)13,
        Shift = (ushort)16,
        Control = (ushort)17,
        /// <summary>
        /// Equivilant to Alt
        /// </summary>
        Menu = (ushort)18,
        /// <summary>
        /// Equivilant to Menu
        /// </summary>
        Alt = (ushort)18,
        Pause = (ushort)19,
        Capital = (ushort)20,
        HANGEUL = (ushort)21,
        HANGUL = (ushort)21,
        KANA = (ushort)21,
        JUNJA = (ushort)23,
        Final = (ushort)24,
        HANJA = (ushort)25,
        KANJI = (ushort)25,
        Escape = (ushort)27,
        Convert = (ushort)28,
        NonConvert= (ushort)29,
        Accept = (ushort)30,
        ModeChange = (ushort)31,
        Space = (ushort)32,
        Prior = (ushort)33,
        Next = (ushort)34,
        End = (ushort)35,
        Home = (ushort)36,
        Left = (ushort)37,
        Up = (ushort)38,
        Right = (ushort)39,
        Down = (ushort)40,
        Select = (ushort)41,
        Print = (ushort)42,
        Execute = (ushort)43,
        Snapshot = (ushort)44,
        Insert = (ushort)45,
        Delete = (ushort)46,
        Help = (ushort)47,
        D0 = (ushort)48,
        D1 = (ushort)49,
        D2 = (ushort)50,
        D3 = (ushort)51,
        D4 = (ushort)52,
        D5 = (ushort)53,
        D6 = (ushort)54,
        D7 = (ushort)55,
        D8 = (ushort)56,
        D9 = (ushort)57,
        A = (ushort)65,
        B = (ushort)66,
        C = (ushort)67,
        D = (ushort)68,
        E = (ushort)69,
        F = (ushort)70,
        G = (ushort)71,
        H = (ushort)72,
        I = (ushort)73,
        J = (ushort)74,
        K = (ushort)75,
        L = (ushort)76,
        M = (ushort)77,
        N = (ushort)78,
        O = (ushort)79,
        P = (ushort)80,
        Q = (ushort)81,
        R = (ushort)82,
        S = (ushort)83,
        T = (ushort)84,
        U = (ushort)85,
        V = (ushort)86,
        W = (ushort)87,
        X = (ushort)88,
        Y = (ushort)89,
        Z = (ushort)90,
        /// <summary>
        /// Do not mistake, this button is not a modifier.
        /// </summary>
        LWIN = (ushort)91,
        /// <summary>
        /// Do not mistake, this button is not a modifier.
        /// </summary>
        RWIN = (ushort)92,
        Apps = (ushort)93,
        Sleep = (ushort)95,
        NUMPAD0 = (ushort)96,
        NUMPAD1 = (ushort)97,
        NUMPAD2 = (ushort)98,
        NUMPAD3 = (ushort)99,
        NUMPAD4 = (ushort)100,
        NUMPAD5 = (ushort)101,
        NUMPAD6 = (ushort)102,
        NUMPAD7 = (ushort)103,
        NUMPAD8 = (ushort)104,
        NUMPAD9 = (ushort)105,
        Multiply = (ushort)106,
        Add = (ushort)107,
        Seperator = (ushort)108,
        Substract = (ushort)109,
        Decimal = (ushort)110,
        Divide = (ushort)111,
        F1 = (ushort)112,
        F2 = (ushort)113,
        F3 = (ushort)114,
        F4 = (ushort)115,
        F5 = (ushort)116,
        F6 = (ushort)117,
        F7 = (ushort)118,
        F8 = (ushort)119,
        F9 = (ushort)120,
        F10 = (ushort)121,
        F11 = (ushort)122,
        F12 = (ushort)123,
        F13 = (ushort)124,
        F14 = (ushort)125,
        F15 = (ushort)126,
        F16 = (ushort)127,
        F17 = (ushort)128,
        F18 = (ushort)129,
        F19 = (ushort)130,
        F20 = (ushort)131,
        F21 = (ushort)132,
        F22 = (ushort)133,
        F23 = (ushort)134,
        F24 = (ushort)135,
        Numlock = (ushort)144,
        Scroll = (ushort)145,
        [Obsolete("Use 'LButton | Shift' instead")]
        LShift = (ushort)160,
        [Obsolete("Use 'RButton | Shift' instead")]
        RSShift = (ushort)161,
        [Obsolete("Use 'LButton | Control' instead")]
        LControl = (ushort)162,
        [Obsolete("Use 'RButton | Control' instead")]
        RControl = (ushort)163,
        [Obsolete("Use 'LButton | Menu\\Alt' instead")]
        LMenu = (ushort)164,
        [Obsolete("Use 'RButton | Menu\\Alt' instead")]
        RMenu = (ushort)165,
        Browser_Back = (ushort)166,
        Browser_Forward = (ushort)167,
        Browser_Refresh = (ushort)168,
        Browser_Stop = (ushort)169,
        Browser_Search = (ushort)170,
        Browser_Favorites = (ushort)171,
        Browser_Home = (ushort)172,
        Volume_Mute = (ushort)173,
        Volume_Down = (ushort)174,
        Volume_Up = (ushort)175,
        Media_Next_Track = (ushort)176,
        Media_Prev_Track = (ushort)177,
        Media_Stop = (ushort)178,
        Media_Play_Pause = (ushort)179,
        Launch_Mail = (ushort)180,
        Launch_Media_Select = (ushort)181,
        Launch_App1 = (ushort)182,
        Launch_App2 = (ushort)183,
        OEM_1 = (ushort)186,
        OEM_Plus = (ushort)187,
        OEM_Comma = (ushort)188,
        OEM_Minus = (ushort)189,
        OEM_Period = (ushort)190,
        OEM_2 = (ushort)191,
        OEM_3 = (ushort)192,
        OEM_4 = (ushort)219,
        OEM_5 = (ushort)220,
        OEM_6 = (ushort)221,
        OEM_7 = (ushort)222,
        OEM_8 = (ushort)223,
        OEM_102 = (ushort)226,
        ProcessKey = (ushort)229,
        Packet = (ushort)231,
        ATTN = (ushort)246,
        CRSEL = (ushort)247,
        EXSEL = (ushort)248,
        EREOF = (ushort)249,
        Play = (ushort)250,
        Zoom = (ushort)251,
        NoName = (ushort)252,
        PA1 = (ushort)253,
        OEM_Clear = (ushort)254,
    }
    
}